### ISSUE TITLE
Code review current master

### ISSUE THREAD

**Issue by selfthinker** [alphagov/table-editor#1]
As this is a new repository and I didn't create a PR, can someone please code review what's currently in master?
Just add any comments in here.

**Comment by robinwhittleton** [comment]
Mostly looks great!

1. The [font `@import`](https://github.com/alphagov/table-editor/blob/427a05241c269b3cf2c2ccb4a7d03d08a2607860/base.css#L2) will break, and isn’t licensed for github so I’d just drop it.
2. Following on from that, the references to NTA should be removed from [generic-tables.css](https://github.com/alphagov/table-editor/blob/427a05241c269b3cf2c2ccb4a7d03d08a2607860/generic-tables.css). I’d pick a common system font / set of fonts with support for tabular numbers, then turn them on with `font-variant-numeric: tabular-nums`. You’d have to do a bit of research around what works here.
3. [Copyright](https://github.com/alphagov/table-editor/blob/427a05241c269b3cf2c2ccb4a7d03d08a2607860/LICENSE#L2) should Crown Copyright, not GDS (e.g. [Verify’s LICENCE](https://github.com/alphagov/verify-frontend/blob/master/LICENSE))

**Comment by NickColley** [comment]
I think it's super cool!

While watching you use the editor I noticed you struggled a few times to remember where a certain functionality was, I wonder if there's opportunity to make the interface simpler.

Other thing we could do is add text labels rather than relying on tooltips.

**Comment by selfthinker** [comment]
@robinwhittleton, I made all the changes in PR #2. Could you just merge it if you're happy? I will be on holiday, so would otherwise do it when I'm back in 11 days.

I didn't know about `font-variant-numeric`, that's interesting. I put it in, but it's not important to get right in the editor, as long as it's correct on gov.uk (which it will be because `.numeric` will be using the correct font).

@nickcolley, yes, simplifying the interface further would be great. I already simplified a lot. The only two functionalities left which I'd love to extract from various layers of clicks is setting the cell type (header cell or not) and the row type (header, body, footer). Unfortunately I couldn't find a straightforward way of doing that within my available time, so I didn't look further.
I don't plan to fix it now as my time on the project is over. I will probably only fix smaller things if something important comes out of the retro. Unless you know how to easily simplify those two things?

**Comment by robinwhittleton** [comment]
OK, merged https://github.com/alphagov/table-editor/pull/2 which fixes everything in my review. Thanks!
